### ISSUE TITLE
Crash: Soundset with duplicate override UUID

### ISSUE THREAD

**Issue by Finaldeath** [Cjreek/Eos-Toolset#3] opened 2024-01-12 23:38 UTC
Repo file: [soundsets.json](https://github.com/Cjreek/Eos-Toolset/files/13924998/soundsets.json)

There are 2 soundsets in the list with the same "override" UUID; this is kind of intentional, one is an override (I just renamed it a little), one is based off it but with a different name and some different sound files to save me some time.

Not sure why the second (right click soundset: "Duplicate XXX" option) creates the UUID.

Setting the field to `null` in the json for the duplicate fixes it.

**Comment by Cjreek** [comment] 2024-01-13 14:30
Not sure how that happened. If I do it in my own project it works as expected, the override gets the override ID set and the duplicate has override ID set to null.

**Comment by Cjreek** [comment] 2024-05-04 17:41
Fixed in 0.74 (Essentially a duplicate of #17 if I am not misunderstanding something)

**Closed by Cjreek** 2024-05-04 17:41 UTC
